version: '3'
services:
  Eureka:
    container_name: eureka
    build: Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: "eureka"

    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/


    Gateway:
      container_name: gateway
      build: API_Gateway_Server
      hostname: gateway
      ports:
        - "8090:8090"
      image: "gateway"
      depends_on:
        - Eureka
        - db-mysql

      environment:
        - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

    db-mysql:
      image: "mysql:5.6"
      container_name: db-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3307:3307"
      restart: unless-stopped


