version: '3'
services:
  eureka-server:
    image: your-eureka-server-image:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  microservice1:
    image: your-microservice1-image:latest
    ports:
      - "8081:8080"
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

  microservice2:
    image: your-microservice2-image:latest
    ports:
      - "8082:8080"
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

networks:
  microservices-network:

