version: "3.9"
services:
  Event:
    container_name: eventMS
    image: "image_ms_docker_event_project"
    build: .\EventProject
    ports:
      - "8040:8040"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
    depends_on:
      - "Eureka"


  Gateway:
    container_name: gateway
    image: "api_gateway"
    build: .\API_Gateway_Server
    ports:
      - "8030:8030"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
    depends_on:
      - Event
      - Eureka



  Eureka:
    container_name: eurekaTest
    build: .\Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: "eureka"

    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/


